# Generated by Django 4.2.5 on 2023-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
