# Generated by Django 4.2.5 on 2023-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
