# Generated by Django 4.2.5 on 2023-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_product_stock_qty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.IntegerField(default=0),
        ),
    ]
