# Generated by Django 4.2.6 on 2023-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_product_description_alter_product_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.JSONField(),
        ),
    ]
