# Generated by Django 4.2.6 on 2023-10-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_order_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
