# Generated by Django 4.2.6 on 2023-10-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_remove_customer_user_customer_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
