# Generated by Django 4.2.6 on 2023-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
